version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Code checked out"

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run build
          command: npm run build

  push:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Convert script to Unix format
          command: sed -i 's/\r$//' push_script.sh
      - run:
          name: Set execute permission
          command: chmod +x push_script.sh
      - run:
          name: Push application
          command: ./push_script.sh

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Pull Docker Image
          command: docker pull suvarotz/myapp:latest
      - run:
          name: Run Docker Container
          command: docker run -d -p 80:80 suvarotz/myapp:latest
      - run:
          name: Install ngrok
          command: |
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
            echo "deb https://ngrok-agent.s3.amazonaws.com/debian stable main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
            sudo apt update && sudo apt install ngrok
      - run:
          name: Configure ngrok Authtoken
          command: ngrok config add-authtoken 2o8qcBoEcwyfxCbyHvJaxTc9hY5_6ibsr5Rh86hCW1WcY2gEd
      - run:
          name: Start ngrok
          command: ngrok http 80 &  # ใช้ & เพื่อรัน ngrok ใน background

workflows:
  version: 2
  push_flow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push  
