version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Code checked out"

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run build
          command: npm run build

  push:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Convert script to Unix format
          command: sed -i 's/\r$//' push_script.sh
      - run:
          name: Set execute permission
          command: chmod +x push_script.sh
      - run:
          name: Push application
          command: ./push_script.sh

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Pull Docker Image
          command: docker pull suvarotz/myapp:latest
      - run:
          name: Run Docker Container
          command: docker run -d -p 3000:3000 suvarotz/myapp:latest
      - run:
          name: Start ngrok
          command: ./start_ngrok.sh
          
workflows:
  version: 2
  push_flow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push